"""empty message

Revision ID: 09f4d46428e3
Revises: a1d836b2a527
Create Date: 2020-06-17 14:08:48.103408

"""

# revision identifiers, used by Alembic.
revision = '09f4d46428e3'
down_revision = 'a1d836b2a527'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
