"""empty message

Revision ID: 257eeb2e660a
Revises: 1f9f9ecfa046
Create Date: 2020-06-25 09:01:24.741176

"""

# revision identifiers, used by Alembic.
revision = '257eeb2e660a'
down_revision = '1f9f9ecfa046'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
