"""empty message

Revision ID: 8be2f39ce4c9
Revises: 257eeb2e660a
Create Date: 2020-06-25 19:28:58.968016

"""

# revision identifiers, used by Alembic.
revision = '8be2f39ce4c9'
down_revision = '257eeb2e660a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
