"""empty message

Revision ID: 90d373aa8002
Revises: 54f323e0444b
Create Date: 2020-06-22 10:35:57.048974

"""

# revision identifiers, used by Alembic.
revision = '90d373aa8002'
down_revision = '54f323e0444b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
