"""empty message

Revision ID: a1d836b2a527
Revises: ffa9ea92fdfb
Create Date: 2020-06-17 12:22:01.326821

"""

# revision identifiers, used by Alembic.
revision = 'a1d836b2a527'
down_revision = 'ffa9ea92fdfb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
