"""empty message

Revision ID: a738bcd41132
Revises: 9ad6a9d2f07f
Create Date: 2020-06-19 13:36:03.370769

"""

# revision identifiers, used by Alembic.
revision = 'a738bcd41132'
down_revision = '9ad6a9d2f07f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
