"""empty message

Revision ID: b6ecda40c7a5
Revises: c527c6e6a00a
Create Date: 2020-06-23 19:00:56.117385

"""

# revision identifiers, used by Alembic.
revision = 'b6ecda40c7a5'
down_revision = 'c527c6e6a00a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
