"""empty message

Revision ID: c527c6e6a00a
Revises: e33c4de9338b
Create Date: 2020-06-23 18:56:14.080173

"""

# revision identifiers, used by Alembic.
revision = 'c527c6e6a00a'
down_revision = 'e33c4de9338b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
