"""hash col added

Revision ID: ffa9ea92fdfb
Revises: 38c4e85512a9
Create Date: 2020-06-14 18:29:13.982814

"""

# revision identifiers, used by Alembic.
revision = 'ffa9ea92fdfb'
down_revision = '38c4e85512a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
